# Generated by Django 3.2.7 on 2021-12-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('state', models.CharField(choices=[('T', 'TO-DO'), ('I', 'In-Progress'), ('D', 'Done')], default='T', max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
